#!/bin/bash
#PBS -N hermes
#PBS -A UCOR0090
#PBS -j oe
#PBS -k eod
#PBS -q main@desched1
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=4:mpiprocs=4:ngpus=4:mem=400GB


### Set temp to scratch
export TMPDIR=${SCRATCH}/${USER}/temp && mkdir -p $TMPDIR
export scratch_dir="/glade/derecho/scratch/aidenz/"

cd /glade/u/home/aidenz/Documents/repos/HERMES/HERMES/models

### specify desired module environment
module purge
module load conda
module load cuda
conda activate /glade/work/aidenz/conda-envs/cluster

### Compile & Run MPI Program
torchrun --standalone --nproc_per_node=gpu train_ddp.py main 100